"""Canonical authoring capabilities shared by runtime tests and the demo."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


CONTRACT_VERSION = "graphfl-authoring-v1"


def capability_manifest() -> dict[str, Any]:
    common_checks = ["Registry", "Shape", "Finite", "Metadata", "Trace/Artifact"]
    return {
        "schema_version": 2,
        "contract_version": CONTRACT_VERSION,
        "validation": {
            "kind": "actual_component_contract",
            "checks": common_checks,
            "runner": "graphfl component validate <plugin> --component <kind>:<name>",
        },
        "execution": {
            "kind": "mock_fl_execution",
            "storage_key": "graphfl-demo-runs-v2",
        },
        "components": [
            {
                "kind": "source",
                "label": "Source",
                "name": "update_stats",
                "register_api": "register_graph_source",
                "config_key": "graph_source",
                "design_name": "demo_update_stats",
                "parameter": {
                    "key": "feature_count",
                    "label": "features",
                    "type": "integer",
                    "choices": [2, 3],
                    "default": 3,
                },
                "contract": {
                    "input": "client local update arrays",
                    "output": "one finite feature vector per client",
                    "todo": "mean/std and optional positive-ratio features",
                },
            },
            {
                "kind": "builder",
                "label": "Builder",
                "name": "mutual_knn",
                "register_api": "register_graph_builder",
                "config_key": "graph_mode",
                "design_name": "demo_mutual_knn",
                "parameter": {
                    "key": "knn_k",
                    "label": "k",
                    "type": "integer",
                    "choices": [1, 2, 3],
                    "default": 2,
                },
                "contract": {
                    "input": "N x d client representation",
                    "output": "finite symmetric N x N adjacency",
                    "todo": "retain an edge only for mutual top-k neighbors",
                },
            },
            {
                "kind": "aggregation",
                "label": "Aggregation",
                "name": "residual_graph_mix",
                "register_api": "register_aggregation_target",
                "config_key": "aggregation_target",
                "design_name": "demo_residual_graph_mix",
                "parameter": {
                    "key": "beta",
                    "label": "beta",
                    "type": "number",
                    "choices": [0.3, 0.5, 0.7],
                    "default": 0.5,
                },
                "contract": {
                    "input": "client updates and client Laplacian",
                    "output": "shape-preserving post-local updates",
                    "todo": "mix raw and graph-filtered client updates once",
                },
            },
        ],
    }


def render_capabilities_javascript() -> str:
    payload = json.dumps(
        capability_manifest(),
        indent=2,
        ensure_ascii=False,
        sort_keys=True,
    )
    return (
        "/* Generated by graphfl_lab.presentation.capabilities. */\n"
        f"window.GraphFLAuthoringCapabilities = Object.freeze({payload});\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", type=Path)
    args = parser.parse_args(argv)
    rendered = render_capabilities_javascript()
    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "CONTRACT_VERSION",
    "capability_manifest",
    "render_capabilities_javascript",
]
