"""Cross-owner interfaces: imports must use commerce.packages.* consistently."""
from concurrent.futures import Future
from typing import Callable, Protocol, TypeVar, runtime_checkable

from commerce.packages.contracts.types import (
    ComparisonResult, ModelVariant, Payload, PersonalizationResult,
    ServingMode, TensorMap, TrainingResult,
)

T = TypeVar("T")


@runtime_checkable
class RecommenderRuntime(Protocol):
    @property
    def seller_id(self) -> str: ...
    def ingest_purchase_event(self, event: Payload) -> None: ...
    def upsert_catalog_item(self, item: Payload, source_seq: int) -> None: ...
    def predict_local(self, request: Payload, *, model_variant: ModelVariant = "text_relation", mode: ServingMode = "auto") -> Payload: ...
    def get_local_data_ref(self) -> str: ...
    def get_shared_manifest(self, *, model_variant: ModelVariant = "text_relation") -> Payload: ...
    def export_shared_state(self, *, model_variant: ModelVariant = "text_relation") -> TensorMap: ...
    def train_round(self, local_data_ref: str, round_config: Payload, *, model_variant: ModelVariant = "text_relation") -> TrainingResult: ...
    def install_release(self, release: Payload, manifest: Payload, tensors: TensorMap, *, model_variant: ModelVariant = "text_relation") -> None: ...
    def personalize_local(self, local_data_ref: str, personal_config: Payload, *, model_variant: ModelVariant = "text_relation") -> PersonalizationResult: ...
    def compare_local(self, request: Payload) -> ComparisonResult: ...


@runtime_checkable
class SnapshotDigest(Protocol):
    """Optional runtime capability for synthetic FL (D0025). Kept out of RecommenderRuntime
    so a runtime without it still satisfies the main protocol; the FL client refuses
    synthetic rounds on such a runtime instead of trusting its input."""
    def snapshot_digest(self, local_data_ref: str) -> str: ...


class SellerJobExecutor(Protocol):
    def submit(self, operation: Callable[[], T]) -> Future[T]: ...


class FLClientLifecycle(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
